server:
  max-http-header-size: 4048576
  tomcat:
    max-http-post-size: 1000MB  #请求参数长度
  port: 3333
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB  #单个文件的最大上限
      max-request-size: 100MB #单个请求的文件总大小上限
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/locationphoto #?currentSchema=sde
    #url: jdbc:postgresql://192.168.30.18:5432/locationphoto #?currentSchema=sde
    username: postgres
    #password: 1
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
      database: postgresql
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect